# Generated by Django 3.0.7 on 2020-08-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationmessage',
            old_name='chat_id',
            new_name='peer_id',
        ),
    ]
