# Generated by Django 3.0.7 on 2020-08-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200824_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='_id',
        ),
    ]
